name: app_tfg
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.2
  flutter_launcher_icons: ^0.9.0
  image_picker: ^0.8.1+1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  modal_progress_hud_nsn: ^0.3.0
  flutter_reorderable_list: ^1.3.1
  dio: ^4.0.4

  meta: ^1.1.8

  flutter_map: ^0.13.0
  latlong2: any
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/perro_inicio.jpeg
    - assets/images/logo.png

  uses-material-design: true

